CREATE TABLESPACE schoolDB
DATAFILE 'C:/oraclexe/data/school.dbf'
SIZE 1M AUTOEXTEND ON NEXT 1K;

DROP TABLESPACE schoolDB
INCLUDING CONTENTS AND DATAFILES
CASCADE CONSTRAINTS;

CREATE USER scuser IDENTIFIED BY scuser
DEFAULT TABLESPACE schoolDB;

DROP USER scuser CASCADE;

GRANT DBA TO scuser;